spring:
  #  jpa:
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true
  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "*"
        allowedHeaders: "*"
        allowedMethods: "*"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: &connectionUrl jdbc:mysql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:3306}/holberton?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
  #  datasource:
  #    type: com.zaxxer.hikari.HikariDataSource
  #    driverClassName: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://google/pashapay?cloudSqlInstance=pashapay-423917:europe-central2:pashapay&socketFactory=com.google.cloud.sql.mysql.SocketFactory
  #    username: root
  #    password: 009OHu5ER8cZAjIP
  #  cloud:
  #    gcp:
  #      sql:
  #        database-name: pashapay
  #        instance-connection-name: pashapay-423917:europe-central2:pashapay
  #        credentials:
  #          encoded-key: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAicGFzaGFwYXktNDIzOTE3IiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiMjFjZDQxY2MxZDk1YmM5NDEwODRlNzBkNmM1MTIyNGU1MTcwNjBiMiIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFEZmp4bjJQZTcrQzNCZFxuek9BVmJpVy9aZERhRjM3eGxDS2hPbEdWeDFpRGdYOGxBcWd3K2pTVVdTMkVBZ1RqR0dLQ3hxTjVHYXRUT2p4MFxuUDU1ZlJFTktWdTZHWk5OMUYyMStBV2tMcXp6SU0zcUZYSG9LNUpXZ2JlM1hiOCtibDVJeHJndWVKWFJqUXNVaFxuQjJ0Q21rZU1UWmtnUU1kaG5rQnVQZFN1RTBtblJWTVB1UCtFM1BvbU5xQkNVZUI1am02N2VRUGxkL3AvQ2JYbVxubG8wMGhUbDhzMGR4M0Q5dG1WeGdTeE51SGl5blZHRmR5RWc4THp5WldUSHN1Q1VRSCs4amd6eW9Wa3lINzdqSVxuMDVpNWdyeEsrb0g3MXorRzZ6Ti9xM2V6Tk1jWE4wcmJoZlJEMjF3bmY1UU1IeHZZazdtOHpabUpOTGxSSVNjeVxuajZhdjR5NmZBZ01CQUFFQ2dnRUFOdS9xbUZtRjVvWVhHZVhqMTBCWEpGNjM0VEJPOEx6UGVjRmtGU09FdStSUlxudzEyUXlXQmpGV1dJeXR6WUtKcHdjdVN2ZlczeWJTUnRnTCsxZ29HNjY0VExYdGxlSVhNZFpBNmlxc3hzeG1Ib1xuSk9laDBoVjBNNVZ3RWpZVzFZeDh6NXFPbmxGajlaU043dHpzM2RRZDZ2dVN1cHRRbzh1STE4NTMra01oSVdweFxuTE43ZStqRzNLLzQ2N1A3NDIySjNwemFwZ3pGdWsrTktVNmIvQlRWN1JSU1J2OTI2U1hmVWFLTHFKaGo4VWNtUVxuU1dwQmlKWHBuajJVVExqanljUnpOTk9pOHZEZVByK0YvVkhDNnNHMnhESkIvTWh3Ykk4Q1FNUWlNd2w0cnc4cFxudnhERjJEem1qd04rWktnb1B1R1VjSi9rVzc3THNCNmYvc0hoYzhUWU1RS0JnUUQxenI4UW9zdEdWYUppUDZ2SlxuUnhtcG4wU1hnVzRZTGE2Slg1QjM3Slh5WGdJNFF4clREOThMcm9yOHRUR0Z4UHR1cUVTaUZJaCtkOVN5MTdIL1xuMG1CVyt4UVF2OWJ1QkZKUUt0OHk0Z3dXOXVHSGtXOUVJR05DSGNNMUdHeEQrRFdaeG81dGFDTy9DVTNnQ3BVeFxuSkQ4Z0IxdXBmektyZXhsQ21NV1dWUEhtcHdLQmdRRG8xQzk4OVNvdENqWGU3MFlKQzFUcUZxOFlRZGtPWUNRblxuMHI3a1BWTUQvOWMyTHdpNm1nQ2Jub0xzOHNSRkxWQTRYVUMyajg4RTVXV2VUL1pTTnk0Qmx2R05Mandja2F1Ylxua0srTXd3OHNLRG1nQUJiTXFzL2Z0Y1JKN2dqQVIzN1BTOFJZRjg2V0U5aGcrdjh5WEk2cGlhR2I3TVgrUm9rWFxuWFpBQ2I2cHZTUUtCZ0ZudUJ2Y21LQ3FXWCsrRURleDR4OG5JREVkRndpcTBZOXU4aTlWa1NFUEE0eDBFYUFiNlxuRW9kcWwwejNXYVB3T25EMHZROXpaYkNuVkxrTnN3QytUaUxrZnlYVm1lUEF6d0NuZnJ0VitraFlrSkNSdzl4dlxuNFFDcWRPV3pCc0VqU1REMmROdFFNMnZNRXFLNkhIVTdKcUVvTC8vbUducWtjY3hzcWpWaTVKR1hBb0dBYTZYM1xuVXVJVG53RnlpT0crVXQ0dlk1QWJZcTdIU2JNLzVEMjNUdFhmdFNDc0EzeFpuOVVtWk0wMElaUFpGVmJ2R1RCY1xuaEV3WFhsOGx6YjJRMk5CMGIvMjNMeHhxWkpjaGJlckdqK0Y3K1dHYnl4TmZkeitlbndOdWZ2UVVqYnBBc2wySVxucVdaUWVPa3lDUnpqc3doQ1diYXR4dWNCWUNDQ3NBL3RUb01NblNrQ2dZRUEyRG1xcEo4ZWk1SjVIakgzR3NITVxucytFOVJ1T0xnV0djNTFBVUQ0MVFROFk1TGUwaU14WlVMd0ZlVnVYV2RsMFdab2lrcWtiQ3VEN3VKZXRKQnVTSFxuMk1pMllkaFJFUGlJTUlZRzAvS3hzMG1yWHZGMWZLNUxHRTBTbXpKb3lMRG44aVg2dStvaFBBbkFRc3ZjTTkxT1xuRW9XWVAyNUJXRDhUSG1lR200V3BkeFU9XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAicGFzaGFwYXktMjUwQHBhc2hhcGF5LTQyMzkxNy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMDQzMDY0MDI5MzcyMDExMTE5MTciLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L3Bhc2hhcGF5LTI1MCU0MHBhc2hhcGF5LTQyMzkxNy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgInVuaXZlcnNlX2RvbWFpbiI6ICJnb29nbGVhcGlzLmNvbSIKfQo
  #  #    url: &connectionUrl jdbc:mysql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:3306}/pashapay?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

jwt:
  token:
    validity: 60000000
    refresh: 1000000
    prefix: Bearer
  signing:
    key: holbertonholbertonholbertonholbertonholbertonholbertonholbertonholbertonholbertonholbertonholbertonholbertonholbertonholbertonholbertonholbertonholbertonholbertonholbertonholbertonholberton
  authorities:
    key: roles
  header:
    string: Authorization

#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store: /root/keystore.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: mycert

